/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FooterComp: typeof import('./src/components/FooterComp.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    ProjectCard: typeof import('./src/components/ProjectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
